baseURL = "http://va1labh.github.io/"
languageCode = "en-us"
title = "Bored Electron"
theme = "hugo-ink"
paginator.page = 5

enableEmoji = true

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Tech musings and other stuff :satellite: [Vallabh D](https://github.com/va1labh)"

	# Optional 64x64 avatar image.
	avatar = "https://avatars.githubusercontent.com/u/67852658?s=400&u=006e29e33e5d3f0141c633e9e3e4a886eb1e7fc6&v=4"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/va1labh"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
